# Generated by Django 4.0.4 on 2023-01-10 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_create_date_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 16, 53, 10, 253866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 16, 53, 10, 252869, tzinfo=utc)),
        ),
    ]
